require 'rule.shop.item_shop.合成废铁级'
require 'rule.shop.item_shop.合成青铜级'
require 'rule.shop.item_shop.合成白银级'
require 'rule.shop.item_shop.合成黄金级'
require 'rule.shop.item_shop.合成铂金级'
require 'rule.shop.item_shop.合成钻石级'